In [ ]:
import pandas as pd
import seaborn as sns
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
df=pd.read_csv('/content/Copy of sonar data.csv', header= None)

In [ ]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

In [ ]:
df.tail()

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
203,0.0187,0.0346,0.0168,0.0177,0.0393,0.1630,0.2028,0.1694,0.2328,0.2684,...,0.0116,0.0098,0.0199,0.0033,0.0101,0.0065,0.0115,0.0193,0.0157,M
204,0.0323,0.0101,0.0298,0.0564,0.0760,0.0958,0.0990,0.1018,0.1030,0.2154,...,0.0061,0.0093,0.0135,0.0063,0.0063,0.0034,0.0032,0.0062,0.0067,M
205,0.0522,0.0437,0.0180,0.0292,0.0351,0.1171,0.1257,0.1178,0.1258,0.2529,...,0.0160,0.0029,0.0051,0.0062,0.0089,0.0140,0.0138,0.0077,0.0031,M
206,0.0303,0.0353,0.0490,0.0608,0.0167,0.1354,0.1465,0.1123,0.1945,0.2354,...,0.0086,0.0046,0.0126,0.0036,0.0035,0.0034,0.0079,0.0036,0.0048,M
207,0.0260,0.0363,0.0136,0.0272,0.0214,0.0338,0.0655,0.1400,0.1843,0.2354,...,0.0146,0.0129,0.0047,0.0039,0.0061,0.0040,0.0036,0.0061,0.0115,M

In [ ]:
df.shape

(208, 61)

In [ ]:
df.describe()#to view some basic statistical details like percentile, mean, std, etc. of a data frame

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
count,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,...,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000
mean,0.029164,0.038437,0.043832,0.053892,0.075202,0.104570,0.121747,0.134799,0.178003,0.208259,...,0.016069,0.013420,0.010709,0.010941,0.009290,0.008222,0.007820,0.007949,0.007941,0.006507
std,0.022991,0.032960,0.038428,0.046528,0.055552,0.059105,0.061788,0.085152,0.118387,0.134416,...,0.012008,0.009634,0.007060,0.007301,0.007088,0.005736,0.005785,0.006470,0.006181,0.005031
min,0.001500,0.000600,0.001500,0.005800,0.006700,0.010200,0.003300,0.005500,0.007500,0.011300,...,0.000000,0.000800,0.000500,0.001000,0.000600,0.000400,0.000300,0.000300,0.000100,0.000600
25%,0.013350,0.016450,0.018950,0.024375,0.038050,0.067025,0.080900,0.080425,0.097025,0.111275,...,0.008425,0.007275,0.005075,0.005375,0.004150,0.004400,0.003700,0.003600,0.003675,0.003100
50%,0.022800,0.030800,0.034300,0.044050,0.062500,0.092150,0.106950,0.112100,0.152250,0.182400,...,0.013900,0.011400,0.009550,0.009300,0.007500,0.006850,0.005950,0.005800,0.006400,0.005300
75%,0.035550,0.047950,0.057950,0.064500,0.100275,0.134125,0.154000,0.169600,0.233425,0.268700,...,0.020825,0.016725,0.014900,0.014500,0.012100,0.010575,0.010425,0.010350,0.010325,0.008525
max,0.137100,0.233900,0.305900,0.426400,0.401000,0.382300,0.372900,0.459000,0.682800,0.710600,...,0.100400,0.070900,0.039000,0.035200,0.044700,0.039400,0.035500,0.044000,0.036400,0.043900

In [ ]:
df[60].value_counts()

M    111
R     97
Name: 60, dtype: int64

In [ ]:
df.groupby(60).mean()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
60,,,,,,,,,,,,,,,,,,,,,
M,0.034989,0.045544,0.050720,0.064768,0.086715,0.111864,0.128359,0.149832,0.213492,0.251022,...,0.019352,0.016014,0.011643,0.012185,0.009923,0.008914,0.007825,0.009060,0.008695,0.006930
R,0.022498,0.030303,0.035951,0.041447,0.062028,0.096224,0.114180,0.117596,0.137392,0.159325,...,0.012311,0.010453,0.009640,0.009518,0.008567,0.007430,0.007814,0.006677,0.007078,0.006024

In [ ]:
x=df.drop(columns=60,axis=1)

In [ ]:
y=df[60]

In [ ]:
print(x)

         0       1       2       3       4       5       6       7       8   \
0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109
1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337
2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598
3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564
..      ...     ...     ...     ...     ...     ...     ...     ...     ...
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328
204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030
205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258
206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945
207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843

         9   ...      50      51      52      53      54      55      56  \
0    0.2111  ...  0.0232  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180
1    0.2872  ...  0.0125  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140
2    0.6194  ...  0.0033  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316
3    0.1264  ...  0.0241  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050
4    0.4459  ...  0.0156  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072
..      ...  ...     ...     ...     ...     ...     ...     ...     ...
203  0.2684  ...  0.0203  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065
204  0.2154  ...  0.0051  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034
205  0.2529  ...  0.0155  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140
206  0.2354  ...  0.0042  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034
207  0.2354  ...  0.0181  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040

         57      58      59
0    0.0084  0.0090  0.0032
1    0.0049  0.0052  0.0044
2    0.0164  0.0095  0.0078
3    0.0044  0.0040  0.0117
4    0.0048  0.0107  0.0094
..      ...     ...     ...
203  0.0115  0.0193  0.0157
204  0.0032  0.0062  0.0067
205  0.0138  0.0077  0.0031
206  0.0079  0.0036  0.0048
207  0.0036  0.0061  0.0115

[208 rows x 60 columns]

In [ ]:
print(y)

0      R
1      R
2      R
3      R
4      R
      ..
203    M
204    M
205    M
206    M
207    M
Name: 60, Length: 208, dtype: object

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2,stratify=y)
print(x.shape,x_train.shape,x_test.shape)

(208, 60) (166, 60) (42, 60)

In [ ]:
print(y.shape,y_train.shape,y_test.shape)

(208,) (166,) (42,)

In [ ]:
print(x_train,y_train)

         0       1       2       3       4       5       6       7       8   \
18   0.0270  0.0092  0.0145  0.0278  0.0412  0.0757  0.1026  0.1138  0.0794
118  0.0363  0.0478  0.0298  0.0210  0.1409  0.1916  0.1349  0.1613  0.1703
65   0.0176  0.0172  0.0501  0.0285  0.0262  0.0351  0.0362  0.0535  0.0258
21   0.0664  0.0575  0.0842  0.0372  0.0458  0.0771  0.0771  0.1130  0.2353
148  0.0712  0.0901  0.1276  0.1497  0.1284  0.1165  0.1285  0.1684  0.1830
..      ...     ...     ...     ...     ...     ...     ...     ...     ...
70   0.0065  0.0122  0.0068  0.0108  0.0217  0.0284  0.0527  0.0575  0.1054
132  0.0968  0.0821  0.0629  0.0608  0.0617  0.1207  0.0944  0.4223  0.5744
47   0.0373  0.0281  0.0232  0.0225  0.0179  0.0733  0.0841  0.1031  0.0993
28   0.0100  0.0275  0.0190  0.0371  0.0416  0.0201  0.0314  0.0651  0.1896
11   0.0123  0.0309  0.0169  0.0313  0.0358  0.0102  0.0182  0.0579  0.1122

         9   ...      50      51      52      53      54      55      56  \
18   0.1520  ...  0.0045  0.0084  0.0010  0.0018  0.0068  0.0039  0.0120
118  0.1444  ...  0.0250  0.0115  0.0190  0.0055  0.0096  0.0050  0.0066
65   0.0474  ...  0.0088  0.0042  0.0175  0.0171  0.0079  0.0050  0.0112
21   0.1838  ...  0.0135  0.0141  0.0190  0.0043  0.0036  0.0026  0.0024
148  0.2127  ...  0.0154  0.0154  0.0156  0.0054  0.0030  0.0048  0.0087
..      ...  ...     ...     ...     ...     ...     ...     ...     ...
70   0.1109  ...  0.0023  0.0069  0.0025  0.0027  0.0052  0.0036  0.0026
132  0.5025  ...  0.0206  0.0073  0.0081  0.0303  0.0190  0.0212  0.0126
47   0.0802  ...  0.0066  0.0008  0.0045  0.0024  0.0006  0.0073  0.0096
28   0.2668  ...  0.0118  0.0088  0.0104  0.0036  0.0088  0.0047  0.0117
11   0.0835  ...  0.0188  0.0133  0.0265  0.0224  0.0074  0.0118  0.0026

         57      58      59
18   0.0132  0.0070  0.0088
118  0.0114  0.0073  0.0033
65   0.0179  0.0294  0.0063
21   0.0162  0.0109  0.0079
148  0.0101  0.0095  0.0068
..      ...     ...     ...
70   0.0036  0.0006  0.0035
132  0.0201  0.0210  0.0041
47   0.0054  0.0085  0.0060
28   0.0020  0.0091  0.0058
11   0.0092  0.0009  0.0044

[166 rows x 60 columns] 18     R
118    M
65     R
21     R
148    M
      ..
70     R
132    M
47     R
28     R
11     R
Name: 60, Length: 166, dtype: object

In [ ]:
print(x_test,y_test)

         0       1       2       3       4       5       6       7       8   \
134  0.1083  0.1070  0.0257  0.0837  0.0748  0.1125  0.3322  0.4590  0.5526
119  0.0261  0.0266  0.0223  0.0749  0.1364  0.1513  0.1316  0.1654  0.1864
63   0.0067  0.0096  0.0024  0.0058  0.0197  0.0618  0.0432  0.0951  0.0836
73   0.0139  0.0222  0.0089  0.0108  0.0215  0.0136  0.0659  0.0954  0.0786
164  0.0163  0.0198  0.0202  0.0386  0.0752  0.1444  0.1487  0.1484  0.2442
131  0.1150  0.1163  0.0866  0.0358  0.0232  0.1267  0.2417  0.2661  0.4346
49   0.0119  0.0582  0.0623  0.0600  0.1397  0.1883  0.1422  0.1447  0.0487
172  0.0180  0.0444  0.0476  0.0698  0.1615  0.0887  0.0596  0.1071  0.3175
112  0.0454  0.0472  0.0697  0.1021  0.1397  0.1493  0.1487  0.0771  0.1171
96   0.0181  0.0146  0.0026  0.0141  0.0421  0.0473  0.0361  0.0741  0.1398
137  0.0430  0.0902  0.0833  0.0813  0.0165  0.0277  0.0569  0.2057  0.3887
192  0.0056  0.0267  0.0221  0.0561  0.0936  0.1146  0.0706  0.0996  0.1673
7    0.0519  0.0548  0.0842  0.0319  0.1158  0.0922  0.1027  0.0613  0.1465
79   0.0108  0.0086  0.0058  0.0460  0.0752  0.0887  0.1015  0.0494  0.0472
40   0.0068  0.0232  0.0513  0.0444  0.0249  0.0637  0.0422  0.1130  0.1911
36   0.0094  0.0166  0.0398  0.0359  0.0681  0.0706  0.1020  0.0893  0.0381
58   0.0225  0.0019  0.0075  0.0097  0.0445  0.0906  0.0889  0.0655  0.1624
75   0.0202  0.0104  0.0325  0.0239  0.0807  0.1529  0.1154  0.0608  0.1317
1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337
32   0.0195  0.0213  0.0058  0.0190  0.0319  0.0571  0.1004  0.0668  0.0691
179  0.0394  0.0420  0.0446  0.0551  0.0597  0.1416  0.0956  0.0802  0.1618
92   0.0260  0.0192  0.0254  0.0061  0.0352  0.0701  0.1263  0.1080  0.1523
187  0.0368  0.0279  0.0103  0.0566  0.0759  0.0679  0.0970  0.1473  0.2164
87   0.0856  0.0454  0.0382  0.0203  0.0385  0.0534  0.2140  0.3110  0.2837
144  0.0299  0.0688  0.0992  0.1021  0.0800  0.0629  0.0130  0.0813  0.1761
140  0.0412  0.1135  0.0518  0.0232  0.0646  0.1124  0.1787  0.2407  0.2682
104  0.0307  0.0523  0.0653  0.0521  0.0611  0.0577  0.0665  0.0664  0.1460
50   0.0353  0.0713  0.0326  0.0272  0.0370  0.0792  0.1083  0.0687  0.0298
46   0.0308  0.0339  0.0202  0.0889  0.1570  0.1750  0.0920  0.1353  0.1593
128  0.0374  0.0586  0.0628  0.0534  0.0255  0.1422  0.2072  0.2734  0.3070
101  0.0335  0.0134  0.0696  0.1180  0.0348  0.1180  0.1948  0.1607  0.3036
117  0.0228  0.0106  0.0130  0.0842  0.1117  0.1506  0.1776  0.0997  0.1428
82   0.0409  0.0421  0.0573  0.0130  0.0183  0.1019  0.1054  0.1070  0.2302
146  0.1021  0.0830  0.0577  0.0627  0.0635  0.1328  0.0988  0.1787  0.1199
169  0.0130  0.0120  0.0436  0.0624  0.0428  0.0349  0.0384  0.0446  0.1318
201  0.0335  0.0258  0.0398  0.0570  0.0529  0.1091  0.1709  0.1684  0.1865
182  0.0095  0.0308  0.0539  0.0411  0.0613  0.1039  0.1016  0.1394  0.2592
160  0.0258  0.0433  0.0547  0.0681  0.0784  0.1250  0.1296  0.1729  0.2794
136  0.1088  0.1278  0.0926  0.1234  0.1276  0.1731  0.1948  0.4262  0.6828
59   0.0125  0.0152  0.0218  0.0175  0.0362  0.0696  0.0873  0.0616  0.1252
89   0.0235  0.0291  0.0749  0.0519  0.0227  0.0834  0.0677  0.2002  0.2876
78   0.0231  0.0351  0.0030  0.0304  0.0339  0.0860  0.1738  0.1351  0.1063

         9   ...      50      51      52      53      54      55      56  \
134  0.5966  ...  0.0172  0.0180  0.0110  0.0234  0.0276  0.0032  0.0084
119  0.2013  ...  0.0135  0.0222  0.0175  0.0127  0.0022  0.0124  0.0054
63   0.1180  ...  0.0029  0.0048  0.0023  0.0020  0.0040  0.0019  0.0034
73   0.1015  ...  0.0024  0.0062  0.0072  0.0113  0.0012  0.0022  0.0025
164  0.2822  ...  0.0027  0.0077  0.0026  0.0031  0.0083  0.0020  0.0084
131  0.5378  ...  0.0228  0.0099  0.0065  0.0085  0.0166  0.0110  0.0190
49   0.0864  ...  0.0069  0.0025  0.0103  0.0074  0.0123  0.0069  0.0076
172  0.2918  ...  0.0122  0.0122  0.0114  0.0098  0.0027  0.0025  0.0026
112  0.1675  ...  0.0137  0.0120  0.0042  0.0238  0.0129  0.0084  0.0218
96   0.1045  ...  0.0076  0.0223  0.0255  0.0145  0.0233  0.0041  0.0018
137  0.7106  ...  0.0208  0.0176  0.0197  0.0210  0.0141  0.0049  0.0027
192  0.1859  ...  0.0185  0.0072  0.0055  0.0074  0.0068  0.0084  0.0037
7    0.2838  ...  0.0052  0.0081  0.0120  0.0045  0.0121  0.0097  0.0085
79   0.0393  ...  0.0161  0.0029  0.0078  0.0114  0.0083  0.0058  0.0003
40   0.2475  ...  0.0199  0.0173  0.0163  0.0055  0.0045  0.0068  0.0041
36   0.1328  ...  0.0134  0.0141  0.0191  0.0145  0.0065  0.0129  0.0217
58   0.1452  ...  0.0051  0.0034  0.0129  0.0100  0.0044  0.0057  0.0030
75   0.1370  ...  0.0188  0.0127  0.0081  0.0067  0.0043  0.0065  0.0049
1    0.2872  ...  0.0125  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140
32   0.0242  ...  0.0261  0.0157  0.0074  0.0271  0.0203  0.0089  0.0095
179  0.2558  ...  0.0118  0.0146  0.0040  0.0114  0.0032  0.0062  0.0101
92   0.1630  ...  0.0132  0.0118  0.0120  0.0051  0.0070  0.0015  0.0035
187  0.2544  ...  0.0151  0.0105  0.0024  0.0018  0.0057  0.0092  0.0009
87   0.2751  ...  0.0128  0.0172  0.0138  0.0079  0.0037  0.0051  0.0258
144  0.0998  ...  0.0342  0.0459  0.0277  0.0172  0.0087  0.0046  0.0203
140  0.2058  ...  0.0798  0.0376  0.0143  0.0272  0.0127  0.0166  0.0095
104  0.2792  ...  0.0063  0.0321  0.0189  0.0137  0.0277  0.0152  0.0052
50   0.0880  ...  0.0098  0.0163  0.0242  0.0043  0.0202  0.0108  0.0037
46   0.2795  ...  0.0070  0.0167  0.0127  0.0138  0.0090  0.0051  0.0029
128  0.2597  ...  0.0353  0.0118  0.0063  0.0237  0.0032  0.0087  0.0124
101  0.4372  ...  0.0302  0.0244  0.0232  0.0093  0.0159  0.0193  0.0032
117  0.2227  ...  0.0185  0.0098  0.0178  0.0077  0.0074  0.0095  0.0055
82   0.2259  ...  0.0113  0.0028  0.0036  0.0105  0.0120  0.0087  0.0061
146  0.1369  ...  0.1004  0.0709  0.0317  0.0309  0.0252  0.0087  0.0177
169  0.1375  ...  0.0024  0.0084  0.0100  0.0018  0.0035  0.0058  0.0011
201  0.2660  ...  0.0130  0.0120  0.0039  0.0053  0.0062  0.0046  0.0045
182  0.3745  ...  0.0357  0.0181  0.0019  0.0102  0.0133  0.0040  0.0042
160  0.2954  ...  0.0121  0.0091  0.0062  0.0019  0.0045  0.0079  0.0031
136  0.5761  ...  0.0140  0.0455  0.0213  0.0082  0.0124  0.0167  0.0103
59   0.1302  ...  0.0019  0.0041  0.0074  0.0030  0.0050  0.0048  0.0017
89   0.3674  ...  0.0242  0.0083  0.0037  0.0095  0.0105  0.0030  0.0132
78   0.0347  ...  0.0154  0.0106  0.0097  0.0022  0.0052  0.0072  0.0056

         57      58      59
134  0.0122  0.0082  0.0143
119  0.0021  0.0028  0.0023
63   0.0034  0.0051  0.0031
73   0.0059  0.0039  0.0048
164  0.0108  0.0083  0.0033
131  0.0141  0.0068  0.0086
49   0.0073  0.0030  0.0138
172  0.0050  0.0073  0.0022
112  0.0321  0.0154  0.0053
96   0.0048  0.0089  0.0085
137  0.0162  0.0059  0.0021
192  0.0024  0.0034  0.0007
7    0.0047  0.0048  0.0053
79   0.0023  0.0026  0.0027
40   0.0052  0.0194  0.0105
36   0.0087  0.0077  0.0122
58   0.0035  0.0021  0.0027
75   0.0054  0.0073  0.0054
1    0.0049  0.0052  0.0044
32   0.0095  0.0021  0.0053
179  0.0068  0.0053  0.0087
92   0.0008  0.0044  0.0077
187  0.0086  0.0110  0.0052
87   0.0102  0.0037  0.0037
144  0.0130  0.0115  0.0015
140  0.0225  0.0098  0.0085
104  0.0121  0.0124  0.0055
50   0.0096  0.0093  0.0053
46   0.0122  0.0056  0.0020
128  0.0113  0.0098  0.0126
101  0.0377  0.0126  0.0156
117  0.0045  0.0063  0.0039
82   0.0061  0.0030  0.0078
146  0.0214  0.0227  0.0106
169  0.0009  0.0033  0.0026
201  0.0022  0.0005  0.0031
182  0.0030  0.0031  0.0033
160  0.0063  0.0048  0.0050
136  0.0205  0.0178  0.0187
59   0.0041  0.0086  0.0058
89   0.0068  0.0108  0.0090
78   0.0038  0.0043  0.0030

[42 rows x 60 columns] 134    M
119    M
63     R
73     R
164    M
131    M
49     R
172    M
112    M
96     R
137    M
192    M
7      R
79     R
40     R
36     R
58     R
75     R
1      R
32     R
179    M
92     R
187    M
87     R
144    M
140    M
104    M
50     R
46     R
128    M
101    M
117    M
82     R
146    M
169    M
201    M
182    M
160    M
136    M
59     R
89     R
78     R
Name: 60, dtype: object

In [ ]:
model=LogisticRegression()

In [ ]:
model.fit(x_train,y_train)

LogisticRegression()

In [ ]:
x_train_prediction=model.predict(x_train)

In [ ]:
prediction=accuracy_score(x_train_prediction,y_train)

In [ ]:
print(prediction)

0.8072289156626506

In [ ]:
x_test_prediction=model.predict(x_test)

In [ ]:
prediction=accuracy_score(x_test_prediction,y_test)

In [ ]:
print(prediction)

0.8333333333333334

In [ ]:
#convert from tuple to numpy bcz is faster
input_data=(0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,0.1609,0.1582,0.2238,0.0645,0.0660,0.2273,0.3100,0.2999,0.5078,0.4797,0.5783,0.5071,0.4328,0.5550,0.6711,0.6415,0.7104,0.8080,0.6791,0.3857,0.1307,0.2604,0.5121,0.7547,0.8537,0.8507,0.6692,0.6097,0.4943,0.2744,0.0510,0.2834,0.2825,0.4256,0.2641,0.1386,0.1051,0.1343,0.0383,0.0324,0.0232,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032)
nparrays=np.asarray(input_data)
nparray_reshaped=nparrays.reshape([1,-1])
prediction_value=model.predict(nparray_reshaped)
print(prediction_value)

if (prediction_value[0]=='R'):
  print('Rock')
else:
  print('Mine')

['R']
Rock